### ISSUE TITLE
Dostosowanie/modyfikacja algorytmu pszczółek pod nasz projekt

### ISSUE THREAD

**Issue by xxLucia** [pkrucz00/pszczolki#7]
- [x] Ogarnięcie podstawowego algorytmu pszczółek
- [x] Ustalenie/modyfikacja struktur pod algorytm (czy robimy od razu cały jadłospis czy np. dzień po dniu?)
- [x] Ustalenie czy robimy wersję z modyfikacjami (np. _site abandonment_)
- [x] Ustalenie kryterium stopu (liczba iteracji? liczba iteracji przy zmianie najlepszego dotychczasowego rozwiązania o epsilon?)
- [x] Ustalenie wartości zmiennych
- [x] Zmodyfikowanie algorytmu

**Comment by pkrucz00** [comment]
Dodatkowo: należy uwzględnić uwagi od prof. Kwiecień
